import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        /**
         * SHADCN UI SEMANTIC COLORS
         * Ces couleurs utilisent les variables CSS définies dans shadcn-tokens.css
         */
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
          subtle: "hsl(var(--primary-subtle))",
          "subtle-hover": "hsl(var(--primary-subtle-hover))",
          border: "hsl(var(--primary-border))",
          "border-hover": "hsl(var(--primary-border-hover))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          hover: "hsl(var(--secondary-hover))",
          active: "hsl(var(--secondary-active))",
          subtle: "hsl(var(--secondary-subtle))",
          "subtle-hover": "hsl(var(--secondary-subtle-hover))",
          border: "hsl(var(--secondary-border))",
          "border-hover": "hsl(var(--secondary-border-hover))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          hover: "hsl(var(--destructive-hover))",
          subtle: "hsl(var(--destructive-subtle))",
          "subtle-hover": "hsl(var(--destructive-subtle-hover))",
          border: "hsl(var(--destructive-border))",
          "border-hover": "hsl(var(--destructive-border-hover))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          hover: "hsl(var(--success-hover))",
          subtle: "hsl(var(--success-subtle))",
          "subtle-hover": "hsl(var(--success-subtle-hover))",
          border: "hsl(var(--success-border))",
          "border-hover": "hsl(var(--success-border-hover))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          hover: "hsl(var(--warning-hover))",
          subtle: "hsl(var(--warning-subtle))",
          "subtle-hover": "hsl(var(--warning-subtle-hover))",
          border: "hsl(var(--warning-border))",
          "border-hover": "hsl(var(--warning-border-hover))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          hover: "hsl(var(--info-hover))",
          subtle: "hsl(var(--info-subtle))",
          "subtle-hover": "hsl(var(--info-subtle-hover))",
          border: "hsl(var(--info-border))",
          "border-hover": "hsl(var(--info-border-hover))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        surface: "hsl(var(--surface))",
        "surface-secondary": "hsl(var(--surface-secondary))",

        /**
         * COULEURS RADIX DIRECTES
         * Accès direct aux échelles de couleurs Radix pour des cas spécifiques
         */
        purple: {
          1: "var(--purple-1)",
          2: "var(--purple-2)",
          3: "var(--purple-3)",
          4: "var(--purple-4)",
          5: "var(--purple-5)",
          6: "var(--purple-6)",
          7: "var(--purple-7)",
          8: "var(--purple-8)",
          9: "var(--purple-9)",
          10: "var(--purple-10)",
          11: "var(--purple-11)",
          12: "var(--purple-12)",
          surface: "var(--purple-surface)",
        },
        orange: {
          1: "var(--orange-1)",
          2: "var(--orange-2)",
          3: "var(--orange-3)",
          4: "var(--orange-4)",
          5: "var(--orange-5)",
          6: "var(--orange-6)",
          7: "var(--orange-7)",
          8: "var(--orange-8)",
          9: "var(--orange-9)",
          10: "var(--orange-10)",
          11: "var(--orange-11)",
          12: "var(--orange-12)",
          surface: "var(--orange-surface)",
          "bg-light": "var(--orange-bg-light)",
        },
        green: {
          1: "var(--green-1)",
          2: "var(--green-2)",
          3: "var(--green-3)",
          4: "var(--green-4)",
          5: "var(--green-5)",
          6: "var(--green-6)",
          7: "var(--green-7)",
          8: "var(--green-8)",
          9: "var(--green-9)",
          10: "var(--green-10)",
          11: "var(--green-11)",
          12: "var(--green-12)",
        },
        amber: {
          1: "var(--amber-1)",
          2: "var(--amber-2)",
          3: "var(--amber-3)",
          4: "var(--amber-4)",
          5: "var(--amber-5)",
          6: "var(--amber-6)",
          7: "var(--amber-7)",
          8: "var(--amber-8)",
          9: "var(--amber-9)",
          10: "var(--amber-10)",
          11: "var(--amber-11)",
          12: "var(--amber-12)",
        },
        red: {
          1: "var(--red-1)",
          2: "var(--red-2)",
          3: "var(--red-3)",
          4: "var(--red-4)",
          5: "var(--red-5)",
          6: "var(--red-6)",
          7: "var(--red-7)",
          8: "var(--red-8)",
          9: "var(--red-9)",
          10: "var(--red-10)",
          11: "var(--red-11)",
          12: "var(--red-12)",
        },
        blue: {
          1: "var(--blue-1)",
          2: "var(--blue-2)",
          3: "var(--blue-3)",
          4: "var(--blue-4)",
          5: "var(--blue-5)",
          6: "var(--blue-6)",
          7: "var(--blue-7)",
          8: "var(--blue-8)",
          9: "var(--blue-9)",
          10: "var(--blue-10)",
          11: "var(--blue-11)",
          12: "var(--blue-12)",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
